### PR TITLE
Fix curl not following GPG key URL redirect

### LINKED ISSUE #63: GPG key doesn't download due to lack of curl following redirects
Download of GPG key in `apt.sh` for the APT install will fail given the current packagecloud.io infrastructure. This is due to the url `https://packagecloud.io/headmelted/codebuilds/gpgkey` issuing a redirect to the eventual location and unfortunately `apt.sh` does not use `curl` in a manner that will follow redirects.

The fix is to change line 28 of the script from:
```sh
curl $gpg_key | gpg --dearmor > /etc/apt/trusted.gpg.d/${REPO_VENDOR}_vscode.gpg;
```
to
```sh
curl -L $gpg_key | gpg --dearmor > /etc/apt/trusted.gpg.d/${REPO_VENDOR}_vscode.gpg;
```

This could be related to the multiple GPG problems like in issue #61

### LINKED ISSUE #71: Could not install GPG key error
Hi,

I'm trying to install VS Studio on a clean Raspbian install on a Raspberry Pi 3, and I'm getting a problem with the GPG Key.

``` bash
root@raspberrypi:/home/pi# . <( wget -O - https://code.headmelted.com/installers/apt.sh )
--2019-03-20 09:42:47--  https://code.headmelted.com/installers/apt.sh
Resolving code.headmelted.com (code.headmelted.com)... 104.27.187.80, 104.27.186.80, 2606:4700:30::681b:bb50, ...
Connecting to code.headmelted.com (code.headmelted.com)|104.27.187.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-sh]
Saving to: ‘STDOUT’

-                                         [ <=>                                                                    ]   2.29K  --.-KB/s    in 0s      

2019-03-20 09:42:47 (6.47 MB/s) - written to stdout [2349]

Detecting architecture...
Ensuring curl is installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Architecture detected as armv7l...
Retrieving GPG key [headmelted] (https://packagecloud.io/headmelted/codebuilds/gpgkey)...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gpg: no valid OpenPGP data found.
```

I managed to work around it by downloading the script, and uncommenting the line with the `--allow-unauthenticated` bit.

``` bash
apt-get install -t ${repo_name} -y ${code_executable_name};
#apt-get install -t ${repo_name} -y --allow-unauthenticated ${code_executable_name};
````

The funny thing is that I swear this worked yesterday, with an old Raspbian install. I've tried #63 but that doesn't help. Any clues?

### PR DESCRIPTION
**Pull request by ZimbiX**
Fixes #63; fixes #71.

### CODE REVIEW

**Comment by pfeerick** [comment]
`https://code.headmelted.com/installers/apt.sh` is still having issues with the redirect as this hasn't been included yet. A call to `apt-key add` may also be needed to NO_PUBKEY warnings

**Comment by Silerra** [comment]
This fix help for me to install code-oss. But the code installation try to update self the gpg-key without the flag '-L' on curl. Somehow I don't know why the installation routine executed twice in the middle.

The second routine overwrite the gpg key and then is the trusted gpg file empty.

**Comment by ZimbiX** [comment]
@headmelted Can we get this merged?

**Comment by mojoTX** [comment]
This project is starting to look like "abandoned-ware."  Open-source is a labor of love, and I appreciate the work that @headmelted put into this, but it may be time to fork if he's too busy to add a new maintainer.

**Comment by pfeerick** [comment]
Looks like the boss is back on deck as 38e4efe8994f2325d6474854e1c2a125d68ec183 has been pushed which resolves this issue :)

**Pull request closed without merging**
